version: "3.9"
services:
   postgres:
      image: postgres:16
      container_name: eventra
      restart: always
      environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         POSTGRES_DB: eventra
      ports:
         - "5432:5432"
      volumes:
         - type: volume
           source: eventra-data
           target: /var/lib/postgresql/data

volumes:
   eventra-data:
      external: false
      name: eventra-data
